spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mail:
    host: localhost
    port: 1025
    username: omar
    password: omar
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 533c6fce6afe12b3ff1f9bac969c78d270547cf45de41e58518b24b1986d6145
      expiration: 86400000 # 1 day
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088